---
title: "p8105_hw2_nrl2142"
output: github_document
date: "2025-09-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library (tidyverse)
```
## Problem 1

## Cleaning pols-month.csv data 
```{r}
polsmonth_df = read_csv ("/Users/gorgeous/Desktop/fivethirtyeight_datasets/pols-month.csv") |>
  janitor::clean_names() |>
  separate(mon, into = c("year", "month", "day"), sep = "-") |>
  mutate (month = month.name [as.numeric (month)]) |>
  mutate (year = as.integer(year)) |>
  pivot_longer(
    cols = c("prez_gop","prez_dem"),
    names_to = "president",
    values_to = "polstance") |>
  mutate (president = case_match(
          president,
          "prez_gop" ~ "gop",
          "prez_dem" ~ "dem")) |>
  select (-polstance,-day) |>
  relocate(year, month)

polsmonth_df

```

## Cleaning snp.csv data
```{r}
snp_df = read_csv("/Users/gorgeous/Desktop/fivethirtyeight_datasets/snp.csv") |>
  janitor::clean_names() |>
  separate(date, into = c("month", "day", "year"), sep = "/") |>
  mutate (month = month.name [as.numeric (month)]) |>
  mutate (year = 2000 + as.integer (year)) |>
  select (-day) |>
  relocate (year,month)
  
  snp_df
```

##Cleaning unemployment data 
```{r}
unemployment_df = read_csv("/Users/gorgeous/Desktop/fivethirtyeight_datasets/unemployment.csv") |>
  janitor::clean_names() |>
  pivot_longer(
    cols = jan:dec,
    names_to = "month",
    values_to = "unemployment_percent") |>
  relocate (year, month)

unemployment_df
```

## Merging snp data into pols data
```{r}
snppolsmerge_df =
  left_join (snp_df, polsmonth_df, by = c("year", "month")) |>
  relocate (year, month)
```

## Merging result with unemployment
```{r}
finalmerge_df =
  left_join (snppolsmerge_df, unemployment_df, by = c("year", "month")) |>
  relocate (year, month)

finalmerge_df
```
## Short descriptive paragraph 

## Problem 2

##Cleaning Mr. Trash Wheel sheet 
```{r}
mrtrashwheel_df = 
  readxl::read_excel ("/Users/gorgeous/Desktop/fivethirtyeight_datasets/202409 Trash Wheel Collection Data.xlsx", sheet = 1, na = c("NA", ".","")) |>
  janitor::clean_names() |>
  filter (!is.na(dumpster)) |>
  mutate (sports_balls = as.integer(round(sports_balls)),
          trash_wheel = "Mr Trash Wheel",
          year = as.integer (year))
```

## Cleaning Professor Trash Wheel sheet 
```{r}
professortrashwheel_df = 
  readxl::read_excel ("/Users/gorgeous/Desktop/fivethirtyeight_datasets/202409 Trash Wheel Collection Data.xlsx", sheet = 2, na = c("NA", ".","")) |>
  janitor::clean_names() |>
  filter (!is.na(dumpster)) |>
  mutate (trash_wheel = "Professor Trash Wheel",
          year = as.integer (year))
```

## Cleaning Gwynnda sheet 
```{r}
gwynnda_df = 
  readxl::read_excel ("/Users/gorgeous/Desktop/fivethirtyeight_datasets/202409 Trash Wheel Collection Data.xlsx", sheet = 4, na = c("NA", ".","")) |>
  janitor::clean_names() |>
  filter (!is.na(dumpster)) |>
  mutate (trash_wheel = "Gywnnda",
          year = as.integer (year))
```

## Merging all three datasets together

```{r}
trashwheel_combined = 
  bind_rows (mrtrashwheel_df, professortrashwheel_df, gwynnda_df) |>
  janitor::clean_names()

trashwheel_combined
  
```

## Short descriptive paragraph 









