p8105_hw2_nrl2142
================
2025-09-29

## Creating directory

``` r
dir.create ("hw2_data")
```

    ## Warning in dir.create("hw2_data"): 'hw2_data' already exists

## Problem 1

## Cleaning pols-month.csv data

``` r
polsmonth_df = read_csv ("/Users/gorgeous/p8105_hw2_nrl2142/hw2_data/fivethirtyeight_datasets/pols-month.csv") |>
  janitor::clean_names() |>
  separate(mon, into = c("year", "month", "day"), sep = "-") |>
  mutate (month = month.name [as.numeric (month)]) |>
  mutate (year = as.integer(year)) |>
  pivot_longer(
    cols = c("prez_gop","prez_dem"),
    names_to = "president",
    values_to = "polstance") |>
  mutate (president = case_match(
          president,
          "prez_gop" ~ "gop",
          "prez_dem" ~ "dem")) |>
  select (-polstance,-day) |>
  relocate(year, month)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
polsmonth_df
```

    ## # A tibble: 1,644 × 9
    ##     year month    gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <int> <chr>      <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1  1947 January       23      51     253      23      45     198 gop      
    ##  2  1947 January       23      51     253      23      45     198 dem      
    ##  3  1947 February      23      51     253      23      45     198 gop      
    ##  4  1947 February      23      51     253      23      45     198 dem      
    ##  5  1947 March         23      51     253      23      45     198 gop      
    ##  6  1947 March         23      51     253      23      45     198 dem      
    ##  7  1947 April         23      51     253      23      45     198 gop      
    ##  8  1947 April         23      51     253      23      45     198 dem      
    ##  9  1947 May           23      51     253      23      45     198 gop      
    ## 10  1947 May           23      51     253      23      45     198 dem      
    ## # ℹ 1,634 more rows

## Cleaning snp.csv data

``` r
snp_df = read_csv("/Users/gorgeous/p8105_hw2_nrl2142/hw2_data/fivethirtyeight_datasets/snp.csv") |>
  janitor::clean_names() |>
  separate(date, into = c("month", "day", "year"), sep = "/") |>
  mutate (month = month.name [as.numeric (month)]) |>
  mutate (year = 2000 + as.integer (year)) |>
  select (-day) |>
  relocate (year,month)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
  snp_df
```

    ## # A tibble: 787 × 3
    ##     year month    close
    ##    <dbl> <chr>    <dbl>
    ##  1  2015 July     2080.
    ##  2  2015 June     2063.
    ##  3  2015 May      2107.
    ##  4  2015 April    2086.
    ##  5  2015 March    2068.
    ##  6  2015 February 2104.
    ##  7  2015 January  1995.
    ##  8  2014 December 2059.
    ##  9  2014 November 2068.
    ## 10  2014 October  2018.
    ## # ℹ 777 more rows

\##Cleaning unemployment data

``` r
unemployment_df = read_csv("/Users/gorgeous/p8105_hw2_nrl2142/hw2_data/fivethirtyeight_datasets/unemployment.csv") |>
  janitor::clean_names() |>
  pivot_longer(
    cols = jan:dec,
    names_to = "month",
    values_to = "unemployment_percent") |>
  mutate (month = month.name [match(month, tolower(month.abb))]) |>
  relocate (year, month)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemployment_df
```

    ## # A tibble: 816 × 3
    ##     year month     unemployment_percent
    ##    <dbl> <chr>                    <dbl>
    ##  1  1948 January                    3.4
    ##  2  1948 February                   3.8
    ##  3  1948 March                      4  
    ##  4  1948 April                      3.9
    ##  5  1948 May                        3.5
    ##  6  1948 June                       3.6
    ##  7  1948 July                       3.6
    ##  8  1948 August                     3.9
    ##  9  1948 September                  3.8
    ## 10  1948 October                    3.7
    ## # ℹ 806 more rows

## Merging snp data into pols data

``` r
snppolsmerge_df =
  left_join (snp_df, polsmonth_df, by = c("year", "month")) |>
  relocate (year, month)

snppolsmerge_df
```

    ## # A tibble: 973 × 10
    ##     year month   close gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <dbl> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1  2015 July    2080.      NA      NA      NA      NA      NA      NA <NA>     
    ##  2  2015 June    2063.      31      54     246      18      44     188 gop      
    ##  3  2015 June    2063.      31      54     246      18      44     188 dem      
    ##  4  2015 May     2107.      31      54     245      18      44     188 gop      
    ##  5  2015 May     2107.      31      54     245      18      44     188 dem      
    ##  6  2015 April   2086.      31      54     244      18      44     188 gop      
    ##  7  2015 April   2086.      31      54     244      18      44     188 dem      
    ##  8  2015 March   2068.      31      54     245      18      44     188 gop      
    ##  9  2015 March   2068.      31      54     245      18      44     188 dem      
    ## 10  2015 Februa… 2104.      31      54     245      18      44     188 gop      
    ## # ℹ 963 more rows

## Merging result with unemployment

``` r
finalmerge_df =
  left_join (snppolsmerge_df, unemployment_df, by = c("year", "month")) |>
  relocate (year, month, close, unemployment_percent, president)

finalmerge_df
```

    ## # A tibble: 973 × 11
    ##     year month    close unemployment_percent president gov_gop sen_gop rep_gop
    ##    <dbl> <chr>    <dbl>                <dbl> <chr>       <dbl>   <dbl>   <dbl>
    ##  1  2015 July     2080.                 NA   <NA>           NA      NA      NA
    ##  2  2015 June     2063.                  5.3 gop            31      54     246
    ##  3  2015 June     2063.                  5.3 dem            31      54     246
    ##  4  2015 May      2107.                  5.5 gop            31      54     245
    ##  5  2015 May      2107.                  5.5 dem            31      54     245
    ##  6  2015 April    2086.                  5.4 gop            31      54     244
    ##  7  2015 April    2086.                  5.4 dem            31      54     244
    ##  8  2015 March    2068.                  5.5 gop            31      54     245
    ##  9  2015 March    2068.                  5.5 dem            31      54     245
    ## 10  2015 February 2104.                  5.5 gop            31      54     245
    ## # ℹ 963 more rows
    ## # ℹ 3 more variables: gov_dem <dbl>, sen_dem <dbl>, rep_dem <dbl>

## Short descriptive paragraph

The tidied dataset `polsmonth_df` contained 1644 observations of 9
variables that are related to the number of national politicians who are
democratic or republican at from 1947 to 2015. During the tidying
process, a new key variable `president` was created with values
reflecting the political affliation of a president during a given month
and year. The tidied dataset `snp_df` contained 787 observations of 3
variables, i.e. year, month and close which refers to the closing values
according to to Standard & Poor’s stock market index (S&P). Lastly, the
dataset `unemployment_df` contains 816 observations of 3 variables
(i.e. year, month and unemployment_percent) that reports the percentage
of unemployment in a given month of a given year. When these three
datasets are merged, the `finalmerge_df` gives us 973 observations with
11 variables. Key variables such as year, month, unemployment_percent
and president allows us to see trends in stock market performance and
unemployment rates in relation to the political affliation of the
sitting president (i.e. whether Republican or Democrat).

## Problem 2

\##Cleaning Mr. Trash Wheel sheet

``` r
mrtrashwheel_df = 
  readxl::read_excel ("/Users/gorgeous/p8105_hw2_nrl2142/hw2_data/202509 Trash Wheel Collection Data.xlsx", sheet = 1, na = c("NA", ".","")) |>
  janitor::clean_names() |>
  filter (!is.na(dumpster)) |>
  mutate (sports_balls = as.integer(round(sports_balls)),
          trash_wheel = "Mr Trash Wheel",
          year = as.integer (year))
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
mrtrashwheel_df
```

    ## # A tibble: 707 × 17
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <int> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 697 more rows
    ## # ℹ 11 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, x15 <lgl>,
    ## #   x16 <lgl>, trash_wheel <chr>

## Cleaning Professor Trash Wheel sheet

``` r
professortrashwheel_df = 
  readxl::read_excel ("/Users/gorgeous/p8105_hw2_nrl2142/hw2_data/202509 Trash Wheel Collection Data.xlsx", sheet = 2, na = c("NA", ".","")) |>
  janitor::clean_names() |>
  filter (!is.na(dumpster)) |>
  mutate (trash_wheel = "Professor Trash Wheel",
          year = as.integer (year))

professortrashwheel_df
```

    ## # A tibble: 132 × 14
    ##    dumpster month     year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>    <int> <dttm>                    <dbl>              <dbl>
    ##  1        1 January   2017 2017-01-02 00:00:00        1.79                 15
    ##  2        2 January   2017 2017-01-30 00:00:00        1.58                 15
    ##  3        3 February  2017 2017-02-26 00:00:00        2.32                 18
    ##  4        4 February  2017 2017-02-26 00:00:00        3.72                 15
    ##  5        5 February  2017 2017-02-28 00:00:00        1.45                 15
    ##  6        6 March     2017 2017-03-30 00:00:00        1.71                 15
    ##  7        7 April     2017 2017-04-01 00:00:00        1.82                 15
    ##  8        8 April     2017 2017-04-20 00:00:00        2.37                 15
    ##  9        9 May       2017 2017-05-10 00:00:00        2.64                 15
    ## 10       10 May       2017 2017-05-26 00:00:00        2.78                 15
    ## # ℹ 122 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>, trash_wheel <chr>

## Cleaning Gwynnda sheet

``` r
gwynnda_df = 
  readxl::read_excel ("/Users/gorgeous/p8105_hw2_nrl2142/hw2_data/202509 Trash Wheel Collection Data.xlsx", sheet = 4, na = c("NA", ".","")) |>
  janitor::clean_names() |>
  filter (!is.na(dumpster)) |>
  mutate (trash_wheel = "Gywnns Fall Trash Wheel",
          year = as.integer (year),
          cigarette_butts = as.numeric(cigarette_butts))

gwynnda_df
```

    ## # A tibble: 349 × 13
    ##    dumpster month   year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>  <int> <dttm>                    <dbl>              <dbl>
    ##  1        1 July    2021 2021-07-03 00:00:00        0.93                 15
    ##  2        2 July    2021 2021-07-07 00:00:00        2.26                 15
    ##  3        3 July    2021 2021-07-07 00:00:00        1.62                 15
    ##  4        4 July    2021 2021-07-16 00:00:00        1.76                 15
    ##  5        5 July    2021 2021-07-30 00:00:00        1.53                 15
    ##  6        6 August  2021 2021-08-11 00:00:00        2.06                 15
    ##  7        7 August  2021 2021-08-14 00:00:00        1.9                  15
    ##  8        8 August  2021 2021-08-16 00:00:00        2.16                 15
    ##  9        9 August  2021 2021-08-16 00:00:00        2.6                  15
    ## 10       10 August  2021 2021-08-17 00:00:00        3.21                 15
    ## # ℹ 339 more rows
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>, trash_wheel <chr>

## Merging all three datasets together

``` r
trashwheel_combined = 
  bind_rows (mrtrashwheel_df, professortrashwheel_df, gwynnda_df) |>
  janitor::clean_names()

trashwheel_combined
```

    ## # A tibble: 1,188 × 17
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <int> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 1,178 more rows
    ## # ℹ 11 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, x15 <lgl>,
    ## #   x16 <lgl>, trash_wheel <chr>

## Short descriptive paragraph

Merging `mrtrashwheel_df`, `professortrashwheel_df` and `gwynnda_df`
produces a dataset of 1188 observation with 17 variables. Key variables
in this dataset are `trash_wheel` which names which trash wheel the
associated data is from, `dumpster` which indicates the specific
`dumpster`, `month` and `year` which denote time of observation and
`weight_tons` for a weighed total (in tons) of the amount of trash
picked up by the varying trash wheels. For example, the weighted total
(in tons) of the amount of trash picked up by Professor. Trash Wheel is
282.26 tons. Other variables such as `cigarette_butts` or `wrappers`
reports the volume of category-specific trash. For example, the total
number of cigarette butts picked up by Gwynnda is 1044820.

## Problem 3

## Cleaning Zip.codes csv

``` r
zipcode_df = read_csv ("/Users/gorgeous/p8105_hw2_nrl2142/hw2_data/zillow_data/Zip codes.csv", na = c("NA", ".","")) |>
  janitor::clean_names() |>
  mutate (county = as.character(county)) |>
  rename (date = file_date) |>
  separate (date, into = c("month", "day", "year"), sep = "/") |>
  mutate (year = as.integer(2000 + as.integer(year)),
          month = month.name [as.numeric (month)]) |>
  distinct() |>
  relocate (zip_code,county, year, month, day)
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (4): County, County Code, File Date, Neighborhood
    ## dbl (3): State FIPS, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
zipcode_df
```

    ## # A tibble: 322 × 9
    ##    zip_code county  year month day   state_fips county_code county_fips
    ##       <dbl> <chr>  <int> <chr> <chr>      <dbl> <chr>             <dbl>
    ##  1    10451 Bronx   2007 July  25            36 005               36005
    ##  2    10452 Bronx   2007 July  25            36 005               36005
    ##  3    10453 Bronx   2007 July  25            36 005               36005
    ##  4    10454 Bronx   2007 July  25            36 005               36005
    ##  5    10455 Bronx   2007 July  25            36 005               36005
    ##  6    10456 Bronx   2007 July  25            36 005               36005
    ##  7    10457 Bronx   2007 July  25            36 005               36005
    ##  8    10458 Bronx   2007 July  25            36 005               36005
    ##  9    10459 Bronx   2007 July  25            36 005               36005
    ## 10    10460 Bronx   2007 July  25            36 005               36005
    ## # ℹ 312 more rows
    ## # ℹ 1 more variable: neighborhood <chr>

## Cleaning ZORI data

``` r
zori_df = read_csv ("/Users/gorgeous/p8105_hw2_nrl2142/hw2_data/zillow_data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv",na = c("NA", ".","")) |>
  janitor::clean_names()|>
  pivot_longer (
    cols = x2015_01_31:x2024_08_31,
    names_to = "date",
    values_to ="zori",
    names_prefix ="x") |>
    separate(date, into = c("year", "month", "day"), sep = "_")|>
  mutate (year = as.integer(year),
          month = month.name [as.numeric (month)])|>
  rename (county = county_name,
         zip_code = region_name) |>
  mutate(county = str_replace(county, "County$", ""),
         county = as.character (county)) |>
  distinct() |>
  relocate (zip_code,county, year, month, day)
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
zori_df
```

    ## # A tibble: 17,284 × 13
    ##    zip_code county   year month day   region_id size_rank region_type state_name
    ##       <dbl> <chr>   <int> <chr> <chr>     <dbl>     <dbl> <chr>       <chr>     
    ##  1    11368 "Queen…  2015 Janu… 31        62080         4 zip         NY        
    ##  2    11368 "Queen…  2015 Febr… 28        62080         4 zip         NY        
    ##  3    11368 "Queen…  2015 March 31        62080         4 zip         NY        
    ##  4    11368 "Queen…  2015 April 30        62080         4 zip         NY        
    ##  5    11368 "Queen…  2015 May   31        62080         4 zip         NY        
    ##  6    11368 "Queen…  2015 June  30        62080         4 zip         NY        
    ##  7    11368 "Queen…  2015 July  31        62080         4 zip         NY        
    ##  8    11368 "Queen…  2015 Augu… 31        62080         4 zip         NY        
    ##  9    11368 "Queen…  2015 Sept… 30        62080         4 zip         NY        
    ## 10    11368 "Queen…  2015 Octo… 31        62080         4 zip         NY        
    ## # ℹ 17,274 more rows
    ## # ℹ 4 more variables: state <chr>, city <chr>, metro <chr>, zori <dbl>

## Merging zipcode_df with zori_df

``` r
tidyzillow_df = 
  left_join (zipcode_df, zori_df, by = c("zip_code"), relationship ="many-to-many") |>
  distinct() |>
  relocate (zip_code)

(tidyzillow_df)
```

    ## # A tibble: 17,687 × 21
    ##    zip_code county.x year.x month.x day.x state_fips county_code county_fips
    ##       <dbl> <chr>     <int> <chr>   <chr>      <dbl> <chr>             <dbl>
    ##  1    10451 Bronx      2007 July    25            36 005               36005
    ##  2    10451 Bronx      2007 July    25            36 005               36005
    ##  3    10451 Bronx      2007 July    25            36 005               36005
    ##  4    10451 Bronx      2007 July    25            36 005               36005
    ##  5    10451 Bronx      2007 July    25            36 005               36005
    ##  6    10451 Bronx      2007 July    25            36 005               36005
    ##  7    10451 Bronx      2007 July    25            36 005               36005
    ##  8    10451 Bronx      2007 July    25            36 005               36005
    ##  9    10451 Bronx      2007 July    25            36 005               36005
    ## 10    10451 Bronx      2007 July    25            36 005               36005
    ## # ℹ 17,677 more rows
    ## # ℹ 13 more variables: neighborhood <chr>, county.y <chr>, year.y <int>,
    ## #   month.y <chr>, day.y <chr>, region_id <dbl>, size_rank <dbl>,
    ## #   region_type <chr>, state_name <chr>, state <chr>, city <chr>, metro <chr>,
    ## #   zori <dbl>

## Short descriptive paragraph

The resulting tidy dataset `tidyzillow_df` has a total of 17,687
observations with 21 variables. Key variables in this dataset are
`zipcode`, `zori` which represents the Zillow Observed Rent Index (ZORI)
in New York City between January 2015 and August 2024. The total number
of unique zip codes in this dataset is 320 and the number if unique
neighbourhoods is 43.

## Rental drop

``` r
janprices_df =
tidyzillow_df |>
  select (state, city, neighborhood, zip_code, year.y, month.y, zori, county.y) |>
  filter (month.y == "January", year.y %in% c(2020, 2021)) |>
  group_by (state, city, neighborhood, zip_code, county.y, year.y) |>
  summarise (zori = mean(zori, na.rm = TRUE), .groups = "drop") |>
  pivot_wider (names_from = "year.y", 
               values_from = "zori",
               names_prefix = "jan") |>
  filter (!is.na(jan2020),!is.na(jan2021), !is.na(neighborhood)) |>
  mutate (price_change = jan2021 - jan2020) |>
  arrange (price_change)|>
  slice (1:10)

(janprices_df)
```

    ## # A tibble: 10 × 8
    ##    state city     neighborhood    zip_code county.y jan2020 jan2021 price_change
    ##    <chr> <chr>    <chr>              <dbl> <chr>      <dbl>   <dbl>        <dbl>
    ##  1 NY    New York Lower Manhattan    10007 "New Yo…   6334.   5422.        -913.
    ##  2 NY    New York Lower East Side    10009 "New Yo…   3406.   2692.        -714.
    ##  3 NY    New York Gramercy Park …    10016 "New Yo…   3731.   3019.        -712.
    ##  4 NY    New York Chelsea and Cl…    10001 "New Yo…   4108.   3398.        -710.
    ##  5 NY    New York Lower East Side    10002 "New Yo…   3645.   2935.        -710.
    ##  6 NY    New York Lower Manhattan    10004 "New Yo…   3150.   2444.        -706.
    ##  7 NY    New York Lower Manhattan    10038 "New Yo…   3573.   2876.        -698.
    ##  8 NY    New York Greenwich Vill…    10012 "New Yo…   3629.   2942.        -686.
    ##  9 NY    New York Gramercy Park …    10010 "New Yo…   3697.   3012.        -685.
    ## 10 NY    New York Lower East Side    10003 "New Yo…   3570.   2897.        -673.

## Rental drop write-up

The neighborhood that experienced the lowest drop in rental prices from
January 2020 to 2021 is Lower Manhattan. Not only does Lower Manhattan
appears three times in the table of top 10 zip codes with largest drop
in price from January 2020 to 2021, their average combined rental drop
is -772.048 (3 d.p.) which exceeds the second-largest rental drop listed
in the table (i.e.Lower East Side).
